"""
Ollama Mock Module
Provides a drop-in mock for the `ollama` package when Ollama is not running.
Used for CI/demo purposes when the VLM server is unavailable.

This generates realistic-looking JSON incident analysis + prose reports
based on simple heuristics (frame count, etc.) without any actual ML inference.

Activation:
    Set environment variable DASHCAM_MOCK_OLLAMA=1
    or import this directly for testing.
"""

import json
import random
import time

MOCK_VEHICLES = [
    ["sedan", "SUV"],
    ["car", "motorcycle"],
    ["truck", "compact car"],
    ["sedan", "pickup truck", "motorcycle"],
]

MOCK_FAULT_ANALYSES = [
    "The white SUV appears to have failed to yield at the intersection, "
    "crossing the centre line before the impact occurred. The dashcam vehicle "
    "was travelling at a lawful speed with right of way.",
    "The red sedan made an abrupt lane change without signalling, directly "
    "into the path of the dashcam vehicle. The evasive braking is visible in "
    "the post-incident frame, indicating the dashcam driver attempted to avoid collision.",
    "The motorcycle overtook on the left on a single-lane road and collided "
    "with an oncoming vehicle. Both vehicles appear to share partial responsibility.",
]

MOCK_PROSE = [
    ("On {date}, a traffic incident was recorded by the onboard dashcam unit. "
     "The footage depicts a {sev} collision involving a {v1} and a {v2} at an "
     "intersection under {weather} conditions. The {v2} failed to yield right-of-way, "
     "crossing the central divider prior to impact. Road surfaces were {road}. "
     "Visibility was assessed as {vis}. Based on the sequence of events captured, "
     "the {v2} operator bears primary responsibility for the incident. "
     "Recommended follow-up: obtain police report, conduct vehicle damage assessment, "
     "and initiate third-party liability proceedings. This report is generated by an "
     "automated AI system and should be verified by a qualified claims adjuster."),
]


class MockOllamaResponse:
    def __init__(self, content: str):
        self.message = {"role": "assistant", "content": content}

    def __getitem__(self, key):
        if key == "message":
            return self.message
        raise KeyError(key)


def build_mock_json(n_frames: int = 3) -> str:
    vehicles = random.choice(MOCK_VEHICLES)
    fault = random.choice(MOCK_FAULT_ANALYSES)
    timeline = [
        "Pre-incident: vehicles approaching at normal traffic speed, road clear.",
        "Impact: sudden velocity change detected; vehicles overlap in frame.",
        "Post-incident: vehicles stationary, visible front-end damage on both.",
    ][:n_frames]
    data = {
        "vehicles": vehicles,
        "fault_analysis": fault,
        "conditions": {
            "road": random.choice(["dry asphalt", "wet asphalt", "dry concrete"]),
            "weather": random.choice(["clear", "overcast", "light rain"]),
            "visibility": random.choice(["good", "moderate"]),
        },
        "severity": random.choice(["minor", "moderate", "severe"]),
        "timeline": timeline,
        "confidence_flag": False,
    }
    return json.dumps(data)


def build_mock_prose(incident_json: dict) -> str:
    v = incident_json.get("vehicles", ["car", "SUV"])
    cond = incident_json.get("conditions", {})
    template = random.choice(MOCK_PROSE)
    return template.format(
        date="27 March 2026",
        sev=incident_json.get("severity", "moderate"),
        v1=v[0] if v else "vehicle",
        v2=v[1] if len(v) > 1 else "second vehicle",
        weather=cond.get("weather", "clear"),
        road=cond.get("road", "dry asphalt"),
        vis=cond.get("visibility", "good"),
    )


def chat(model: str, messages: list, options: dict = None, **kwargs) -> MockOllamaResponse:
    """Mock ollama.chat() — returns realistic incident data without any server."""
    time.sleep(0.4)  # simulated inference delay

    # Detect if this is a VLM call (has images) or prose call
    has_images = any("images" in m for m in messages)

    if has_images:
        n_images = len(messages[-1].get("images", []))
        content = build_mock_json(n_frames=n_images)
    else:
        # Try to extract incident JSON from the user prompt
        user_content = next((m["content"] for m in messages if m["role"] == "user"), "")
        try:
            # Find JSON-like section in prompt
            import re
            match = re.search(r'"severity":\s*"(\w+)"', user_content)
            sev = match.group(1) if match else "moderate"
            mock_data = {"severity": sev, "vehicles": ["car", "SUV"],
                         "conditions": {"weather": "clear", "road": "dry asphalt", "visibility": "good"}}
            content = build_mock_prose(mock_data)
        except Exception:
            content = build_mock_prose({})

    return MockOllamaResponse(content)


def list(**kwargs) -> dict:
    return {"models": [{"name": "minicpm-v"}, {"name": "mistral"}]}
